// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo8CrShCnMjv2WmgrYkEJbWgsHOQArEdA',
    appId: '1:207617388009:web:d4b7f7d0028c8a77026f78',
    messagingSenderId: '207617388009',
    projectId: 'igclone-009',
    authDomain: 'igclone-009.firebaseapp.com',
    storageBucket: 'igclone-009.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcDlVMS_s73y1Adie3ZeLOS1Xw8kP63I',
    appId: '1:207617388009:android:5faa79efe0e73d87026f78',
    messagingSenderId: '207617388009',
    projectId: 'igclone-009',
    storageBucket: 'igclone-009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1wxyYRPxIYmfNpEfMjk1XZlThY72MjfE',
    appId: '1:207617388009:ios:fffb48fe2ffab090026f78',
    messagingSenderId: '207617388009',
    projectId: 'igclone-009',
    storageBucket: 'igclone-009.firebasestorage.app',
    iosBundleId: 'com.example.clonig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1wxyYRPxIYmfNpEfMjk1XZlThY72MjfE',
    appId: '1:207617388009:ios:fffb48fe2ffab090026f78',
    messagingSenderId: '207617388009',
    projectId: 'igclone-009',
    storageBucket: 'igclone-009.firebasestorage.app',
    iosBundleId: 'com.example.clonig',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo8CrShCnMjv2WmgrYkEJbWgsHOQArEdA',
    appId: '1:207617388009:web:ff674e353ab3341f026f78',
    messagingSenderId: '207617388009',
    projectId: 'igclone-009',
    authDomain: 'igclone-009.firebaseapp.com',
    storageBucket: 'igclone-009.firebasestorage.app',
  );
}
